### ISSUE TITLE
bug:unAuthorized 401이슈 에러

### ISSUE THREAD

**Issue by kwangyoulsagong** [BugFlix/server#20]
## 어떤 버그인가요?

> 어떤 버그인지 설명해주세요
프론트 측 내용이 빠지거나 액세스 토큰이 일치 하지않으면 
무한 401 에러 이슈로 통해 refreshToken이 무한으로 요청을 보냄

**Comment by jang-namu** [comment]
입력 매개변수가 잘못되었을 경우, 백엔드에서 유효성검사를 통해 다른 예외로 처리가 가능합니다.
빠른 시일내로 수정하겠습니다.

다만, **"액세스 토큰이 일치하지않으면~"** 해당 부분은 401이 발생하는 것이 정상적인 상황으로
프론트에서 처리로직을 수정할 필요가 있을 것 같습니다.

**Comment by kwangyoulsagong** [comment]
> 입력 매개변수가 잘못되었을 경우, 백엔드에서 유효성검사를 통해 다른 예외로 처리가 가능합니다. 빠른 시일내로 수정하겠습니다.
> 
> 다만, **"액세스 토큰이 일치하지않으면~"** 해당 부분은 401이 발생하는 것이 정상적인 상황으로 프론트에서 처리로직을 수정할 필요가 있을 것 같습니다.

확인했습니다

**Comment by jang-namu** [comment]
해당 이슈는 클라이언트 쪽에서 무한 슈팅을 처리하고, 
서버측의 Validation은 다른 이슈를 생성해서 관리하겠습니다.
